[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jescorecli"
version = "1.0.3"
description = "CLI for jescore serial communication"
authors = [
    { name = "jake-is-ESD-protected", email = "jake@jesdev.io" }
]
dependencies = ["pyserial"]
keywords = ["jescore", "MCU", "serial"]
requires-python = ">=3.9"

[project.urls]
"Homepage" = "https://jesdev.io"

[project.scripts]
jescore = "jescorecli.jescorecli:main"

[project.optional-dependencies]
dev = ["pytest", "ruff", "black"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "C4", "UP", "N", "S", "A", "C90", "T10", "T20"]
ignore = ["E501"]
fixable = ["A", "B", "C4", "E", "F", "I", "N", "S", "T10", "T20", "UP", "W"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*.py" = ["S101"]

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
